# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"foot" = "󰽒"
"github" = ""
"rust" = ""
"google" = ""
"private browsing" = ""
"firefox" = ""
"chrome" = ""
"dolphin" = ""
"thunar" = ""
"nvim" = ""
"zed" = ""
"gthumb" = ""
"transmission" = ""
"vlc" = "󰕼"
".pdf" = ""

[other]
fallback_icon = "󰀻"
deduplicate_icons = true
