ble-face auto_complete='fg=gray'
ble-face region='bg=60,fg=231'
ble-face menu_filter_fixed='fg=cyan'
ble-face syntax_command='fg=green,none'
ble-face syntax_error='fg=red,bg=235,none'
ble-face filename_directory='fg=33'
ble-face filename_directory_sticky='fg=231,bg=26'
ble-face filename_link='fg=teal'
ble-face filename_orphan='fg=16,bg=224'
ble-face filename_setuid='fg=black,bg=220'
ble-face filename_setgid='fg=black,bg=191'
ble-face filename_executable='fg=green'
ble-face filename_other='fg=white'
ble-face filename_socket='fg=cyan,bg=black'
ble-face filename_pipe='fg=lime,bg=black'
ble-face filename_character='fg=231,bg=black'
ble-face filename_block='fg=yellow,bg=black'
ble-face filename_ls_colors='fg=white'
ble-face command_directory='fg=33'

ble-bind -m auto_complete -f TAB auto_complete/insert

bleopt complete_auto_wordbreaks=$' \t\n'
bleopt complete_auto_wordbreaks=$' \t\n/'
