fallback_icon = "󰀻"
separator = ' '

[matching]
'discord' = ''
'balena-etcher' = ''
'Steam' = ''
'vlc' = '󰕼'
'org.qbittorrent.qBittorrent' = ''
'Thunderbird' = ''
'thunderbird' = ''
'Google-chrome' = ''
'google-chrome' = ''
'Chromium' = ''
'Code' = ''
'code-oss' = ''
'jetbrains-studio' = ''
'Spotify' = ''
'GitHub Desktop' = ''
'/(?i)Github.*Firefox/' = ''
'firefox' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'/nvim ?\w*/' = ''
'Alacritty' = ''
'foot' = '󰽒'
'foot-cli' ='󰽒'
"Thunar" = ""
"thunar" = ""
"zed" = ""
"anki" = ""
"write" = ""
"Write" = ""
"xournalpp" = ""
"Xournalpp" = ""
"OpenTabletDriver" = "󱞇"
"obsidian" = ""
"Mission Center" = "󱃫"
'zenity' = ''
".pdf" = ""

